name: CI/CD
on: {pull_request: {branches: ["main"]}}
jobs:
  build:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with: {python-version: '3.11.3'}
      - name: Build
        run: |
          rm -rf ./dist ./build ./.pyarmor ~/macos-venv ./test.spec ./obfdist
          python3 -m venv ~/macos-venv/ && chmod +x ~/macos-venv/bin/activate && ~/macos-venv/bin/activate
          pip install --upgrade --force-reinstall pyinstaller==5.11.0 pyarmor==8.3.1 pyarmor.cli.core.darwin==4.3.1
          mkdir -p "./src/main/python" && touch "./src/main/python/test.py"
          pyi-makespec --name test --target-architecture universal2 ./src/main/python/test.py
          pyinstaller ./test.spec
          ls -a ./dist
          pyarmor gen --platform darwin.x86_64,darwin.arm64 --pack ./dist/test.app/Contents/MacOS/test ./src/main/python/*